
title: "Christopher Wilson"
tagline: ""
description: "Follow <a href=\"https://micro.blog/ChrisJWilson\">@ChrisJWilson on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/ChrisJWilson\">@ChrisJWilson on Micro.blog</a>."
baseurl: ""
url: "http://chrisjwilson.me"
markdown: "kramdown"
username: "ChrisJWilson"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Christopher Wilson"
name: "Christopher Wilson"
gravatar_hash: "3ce9e8d31a85e655218610f8a31ec223"
avatar: "https://micro.blog/ChrisJWilson/avatar.jpg"
full_name: "Christopher Wilson"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "3042"