highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "Chris J Wilson"
tagline: ""
description: "Follow <a href=\"https://micro.blog/ChrisJWilson\">@ChrisJWilson on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/ChrisJWilson\">@ChrisJWilson on Micro.blog</a>."
baseurl: ""
url: "http://chrisjwilson.me"
markdown: "kramdown"
username: "ChrisJWilson"
microblog_user: "ChrisJWilson"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Chris J Wilson"
name: "Chris J Wilson"
gravatar_hash: "3ce9e8d31a85e655218610f8a31ec223"
avatar: "https://micro.blog/ChrisJWilson/avatar.jpg"
full_name: "Chris J Wilson"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "3042"
gems: ["jekyll-paginate"]
itunes_description: "Content Writer in Poland, Christian, Sketchnoter, and heavy iPad user."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Christopher Wilson"
itunes_email: ""
podcast: false